### ISSUE TITLE
Can you use any js library in karax? 

### ISSUE THREAD

**Issue by nixfreak** [ajusa/simple-chat#1]
Hello, I'm usually in the nim-webdev channel, can you use any js library in karax? 

I'm really trying to figure out how to use https://github.com/orbitdb/orbit-db and maybe something like https://github.com/stellar/js-stellar-sdk. 

If I could use karax for this that would be awesome.

**Comment by ajusa** [comment]
Yes, but this isn't the right place for this discussion (this repository doesn't have any actual code related to Karax other than usage of the DSL). I would recommend looking at https://nim-lang.org/docs/jsffi.html along with asking folks in the Nim discord for examples of jsffi in Nim. It is pretty doable to be honest - the trickiest bit is working with types, as Nim is strongly typed and Javascript is dynamically typed.

**Comment by nixfreak** [comment]
Thank you for your time.
